### ISSUE TITLE
connecting the jungle testnet ,but "cleos get account linlibinieos" is does not work

### ISSUE THREAD

**Issue by StupidStudentInSchool** [CryptoLions/EOS-Jungle-Testnet#28]
> config.ini配置了p2p-server-addrass,producer-name,还有signature-provider[图片]连接上了jungle network了吧 但是为什么我创建的账号 信息查不到

**Comment by lixiaosi33** [comment]
> > config.ini配置了p2p-server-addrass,producer-name,还有signature-provider[图片]连接上了jungle network了吧 但是为什么我创建的账号 信息查不到

大哥，你是怎么解决的

**Comment by qq29oo** [comment]
应该是要等到你的区块数据同步到最新的块，才能查看到你的账户信息，因为创建账户也是一个发起交易的过程
