### ISSUE TITLE
if not support history, why we need this testnet???????????

### ISSUE THREAD

**Issue by Petelin** [CryptoLions/EOS-Jungle-Testnet#35]
i have no idea why all node not support history plugin. what is this net working for? dapp alway need  history

**Comment by ansigroup** [comment]
Hi, there are few:
http://junglehistory.cryptolions.io:18888 (https://junglehistory.cryptolions.io)
https://api.jungle.alohaeos.com

**Comment by rockandruby** [comment]
@ansigroup what're the api endpoints of above servers or any docs how to use them? For sample EOS team told me 

> Send a get_blocks_request_v0 with an end_block_num in the future. This acts as a subscription.
So how to send this request?

**Comment by ansigroup** [comment]
Full History nodes (filter-on = *)
   http://junglehistory.cryptolions.io:18888 
   https://junglehistory.cryptolions.io:443 
Mongo History:
   http://junglehistory.cryptolions.io
   https://junglehistory.cryptolions.io:4433/	

Info about history endpoints you can find in telegram group: https://t.me/jungletestnet (pinned message)
or in monitor legend: https://monitor.jungletestnet.io/

**Comment by ansigroup** [comment]
docs for mongodb history you can find on mongo API: https://junglehistory.cryptolions.io:4433/
for classic history: https://developers.eos.io/eosio-nodeos/reference

**Comment by rockandruby** [comment]
@ansigroup thanks for answer but seems my question was misunderstood. Ok, I'll rephrase it. I need to implement analogue of bitcoin walletnotify(or listtransactions). How can I do that via rpc?

**Comment by rockandruby** [comment]
@ansigroup  seems I understood the point. So I connect to your history node and then use get_actions. Am I right?

**Comment by ansigroup** [comment]
yes

**Comment by jimmyyao88** [comment]
> yes

HI , i use jungle test net and cannot reach history api ,  always report  Error: {"message":"NODEOS_UNREACHABLE","code":503
I use this node : http://junglehistory.cryptolions.io:18888 ,which you mentioned above, it works a few days ago, any idea?

**Comment by jimmyyao88** [comment]
and i'm running a loop to fetch the api and check something , the interval duration is about 300ms, Do the server have something like blacklist , and my server have been blocked?

**Comment by ansigroup** [comment]
Hello, sorry, but today our Jungle history crashed.. we are in replay process, and shortly will be back
