### ISSUE TITLE
 ./start.sh doesn't work

### ISSUE THREAD

**Issue by JamesZH29** [CryptoLions/EOS-Jungle-Testnet#36]
When running ./start.sh   , comes following

> JungleTestnet-vcchaintest5/stop.sh: line 16: kill: (70075) - No such process
> Nodeos stopped. 
> Starting Nodeos 
> 
> ./start.sh: line 16: ulimit: open files: cannot modify limit: Invalid argument

Any idea how to fix it?

That's what in start.sh file:

> ODEOS=/Users/vcchain/eos-source/build/programs/nodeos/nodeos
> DATADIR=/Users/vcchain/JungleTestnet-vcchaintest5
> $DATADIR/stop.sh
> echo -e "Starting Nodeos \n";
> 
> ulimit -n 65535
> ulimit -s 64000
> 
> 
> $NODEOS --data-dir $DATADIR --config-dir $DATADIR "$@" > $DATADIR/stdout.txt 2> $DATADIR/stderr.txt &  echo $! > **$DATADIR/nodeos.pid**

**Comment by ansigroup** [comment]
Hi,

what OS version do you use? this scripts were tested for ubuntu/centos

**Comment by JamesZH29** [comment]
I'm using Darwin, macOS High Sierra 10.13.6

**Comment by ansigroup** [comment]
probably you dont have ulimit command, try to comment it out. Also please check logs, maybe you va some other errors why nodeos do not start
