### ISSUE TITLE
apply for BP

### ISSUE THREAD

**Issue by tinyhill666** [CryptoLions/EOS-Jungle-Testnet#4]
Server location: Shanghai, China.
Organization: EOSeco
Node domain: jungle.eoseco.net
Port(http): 8888
Port(p2p): 9876
Producer name: hummingbird
Public Key: EOS85fDTxvb2P6cXuz5nQyaDwTPbemwcw6KyVDmHHZaGFNog5fBCK

**Comment by wupeaking** [comment]
@qiushaoxi  I want to connect the jungle‘s testnet , but it always shows  some words like " received a go away message from dev.cryptolions.io  reason = wrong chain ". Can you help me？
